<?php
/**
 * @file slick.module
 *
 * @ingroup slick
 *
 * Includes hook implementations required for the Slick module
 *
 */

/**
 * Implements hook_theme
 */
function slick_theme() {
  $return = array();
  $defaults = array(
    'file' => 'slick.pages.inc',
  );

  $return['slick_slideshow'] = $defaults + array(
    'variables' => array(
      'slides' => NULL,
      'slick_settings' => NULL,
      'slideshow_id' => NULL,
      'carousel_nav' => NULL,
      'carousel_id' => NULL,
      'carousel_settings' => NULL,
    ),
  );

  $return['slick_lazy_image'] = $defaults + array(
    'variables' => array(
      'item' => NULL,
      'item_attributes' => NULL,
      'path' => NULL,
      'image_style' => NULL
    ),
  );

  $return['slick_break_point'] = $defaults + array(
    'render element' => 'element',
  );

  return $return;
}