# Schema for the configuration files of the Slick module.

# This schema tells the config system how to read our config YML files.
# See for example the file config/slick.slick_settings.default.yml, which
# contains our default config entity.

# Documentation for schema files like this one is located here:
# https://drupal.org/node/1905070

slick.slick_settings.*:
  type: mapping
  label: 'Slideshow Settings'
  mapping:
    id:
      type: string
      label: 'Entity id'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    slide_image_style:
      type: string
      label: 'Slide Image Style'
    accessibility:
      type: boolean
      label: 'Accessibility'
    adaptive_height:
      type: boolean
      label: 'Adaptive Height'
    autoplay:
      type: boolean
      label: 'Autoplay'
    autoplay_speed:
      type: integer
      label: 'Autoplay Speed'
    arrows:
      type: boolean
      label: 'Arrows'
    as_nav_for:
      type: string
      label: 'As Navigation For'
    carousel_nav:
      type: boolean
      label: 'Carousel Navigation'
    append_arrows:
      type: string
      label: 'Append Arrows'
    prev_arrow:
      type: string
      label: 'Previous Arrow'
    next_arrow:
      type: string
      label: 'Next Arrow'
    center_mode:
      type: boolean
      label: 'Center Mode'
    center_padding:
      type: string
      label: 'Center Padding'
    css_ease:
      type: string
      label: 'CSS3 Easing'
    custom_paging:
      type: string
      label: 'Custom Paging'
    responsive:
      type: mapping
      label: 'Breakpoints'
      mapping:
        pixel_width:
          type: integer
          label: 'Pixel Width'
        settings_eid:
          type: string
          label: 'Slideshow Settings'